### PR TITLE
Update community with new board instructions, new meeting info and new references

### PR DESCRIPTION
**Pull request by vmayoral**

### CODE REVIEW

**Comment by vmayoral** [comment]
Ping @KiranVishal @jasvinderkhurana and @iormaoro, please review when possible.

**Review by iormaoro — APPROVED** [review]
I understand that links in the example of https://github.com/ros-acceleration/acceleration_firmware_kv260#hardware-acceleration-capabilities are not working yet, as REP-2008 is a proposal and has not gone through yet.
Rest is correct.

**Comment by vmayoral** [comment]
> I understand that links in the example of https://github.com/ros-acceleration/acceleration_firmware_kv260#hardware-acceleration-capabilities are not working yet, as REP-2008 is a proposal and has not gone through yet.
Rest is correct.

That's right. It's pending on the REP to be accepted. Once it gets in, links will work.

Maybe we could put a disclaimer there? I like the idea and encourage you @iormaoro to submit a PR. Nevertheless, that's beyond the scope of this PR, so I think we're fine there.

**Comment by vmayoral** [comment]
@KiranVishal and @jasvinderkhurana, any thoughts from your side? 

Otherwise, with @iormaoro's review, I'll get this in.

**Pull request merged**
